version: 1.0.{build}

before_build:
- cmd: dotnet restore

build:
  verbosity: minimal

after_build:
- ps: if ($env:APPVEYOR_REPO_TAG -eq $true) {dotnet pack src\dotnetcore-nuget -o .\Artifacts} else {dotnet pack src\dotnetcore-nuget -o .\Artifacts --version-suffix=$env:APPVEYOR_BUILD_NUMBER}

artifacts:
- path: .\Artifacts\*

deploy:
- provider: NuGet
  server: https://www.myget.org/F/ilyaf-test-packages/api/v2/package
  api_key:
    secure: pI6WWkSGlLdvpdtDo1sMqeQ3ReWjnCgUtKKrXIZBpJv81xMuhzTygUTTHRK20RXi
  symbol_server: https://www.myget.org/F/ilyaf-test-packages/symbols/api/v2/package
